# Generated by Django 4.0 on 2023-02-03 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dibujo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('token', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, null=True)),
                ('contrasena', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valora',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('id_dibujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='backend_api.dibujo')),
                ('token_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='backend_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('historia', models.TextField(max_length=500)),
                ('createdAt', models.DateField()),
                ('token_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='backend_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('codigo_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='backend_api.partida')),
                ('token_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='backend_api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='dibujo',
            name='token_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dibujos', to='backend_api.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=1000)),
                ('id_dibujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='backend_api.dibujo')),
                ('token_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='backend_api.usuario')),
            ],
        ),
    ]
